apiVersion: apps/v1
kind: Deployment
metadata:
  name: lokacijski-opomniki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lokacijski_opomniki2
  template:
    metadata:
      labels:
        app: lokacijski_opomniki2
    spec:
      containers:
        - image: zigadrab/prpo:lokacijski_opomniki2
          name: lokacijski-opomniki2
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: lokacijski-opomniki-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: lokacijski_opomniki2





