KUMULUZEE_SECURITY_KEYCLOAK_JSON: '{"realm": "customers-realm",
                "bearer-only": true,
                "auth-server-url": "http://localhost:8080/auth",
                "ssl-required": "external",
                "resource": "customers-api"}'
kumuluzee:
  name: simple-jdbc-sample
  version: 1.0.0
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/LokacijskiOpomnikiDS
    connection-url: jdbc:postgresql://localhost:5432/polnilnePostaje
    username: postgres
    password: postgres
  security:
    keycloak:
      json: '{
  "realm": "uporabniki-realm",
  "bearer-only": true,
  "auth-server-url": "http://localhost:8083/auth/",
  "ssl-required": "external",
  "resource": "uporabniki-api",
  "confidential-port": 0
}'
integrations:
  nazadnje:
    base-url: http://localhost:8081/v1
  rezervacije:
    base-url: http://localhost:8082/v1
