kumuluzee:
  name: simple-jdbc-sample
  version: 1.0.0
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/LokacijskiOpomnikiDS
    connection-url: jdbc:postgresql://localhost:5432/nakupovalniseznami
    username: postgres
    password: postgres