kumuluzee:
  name: simple-jdbc-sample
  version: 1.0.0
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/LokacijskiOpomnikiDS
    connection-url: jdbc:postgresql://host.docker.internal:5432/polnilnePostaje
    username: postgres
    password: postgres
  health:
    logs:
      enabled: true
      type: both
      level: FINE
      period-s: 1
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/LokacijskiOpomnikiDS
      disk-space-health-check:
        threshold: 100000000
      http-health-check:
        - connection-url: https://rapidapi.com/Gramzivi/api/covid-19-data
  security:
    keycloak:
      json: '{
  "realm": "uporabniki-realm",
  "bearer-only": true,
  "auth-server-url": "http://localhost:8085/auth/",
  "ssl-required": "external",
  "resource": "uporabniki-api",
  "confidential-port": 0
}'
integrations:
  nazadnje:
    base-url: http://localhost:8081/v1
  rezervacije:
    base-url: http://localhost:8082/v1
